version: "2"
linters:
  enable:
    - misspell
    - revive
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    revive:
      rules:
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
