# docker-compose.yml
version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: goflow_test
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d goflow_test"]
      interval: 5s
      timeout: 5s
      retries: 5


  goflow:
    image: goflow:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["--db", "postgres://testuser:testpass@postgres:5432/goflow_test?sslmode=disable", "--port", "8080"]
    depends_on:
      - postgres

volumes:
  postgres_data: