name: GoFlow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' 

      - name: Install dependencies
        run: |
          go mod download
          #go install golang.org/x/lint/golangci-lint@v1.61.0
          #go install github.com/joho/godotenv/cmd/godotenv@latest  # For test target

      - name: Format code
        run: make fmt

      - name: Vet code
        run: make vet

      - name: Lint code
        run: make lint

      - name: Run tests
        env:
          DB_USERNAME: testuser
          DB_PASSWORD: testpass
          DB_NAME: goflow_test
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          # go run cmd/goflow-migrate/main.go migrate --db "postgres://testuser:testpass@localhost:5433/goflow_test?sslmode=disable"
          go test -race -count=1 -shuffle=on ./...